USE QuanLyPhongKhamNhaKhoa_HQT
GO


CREATE OR ALTER PROCEDURE p_KtraTKKH @SDT NVARCHAR(20), @MATKHAU NVARCHAR(255),
@OK BIT OUT
AS
BEGIN TRANSACTION
	IF EXISTS(SELECT * FROM KhachHang WHERE @SDT = KhachHang.SoDienThoai AND @MATKHAU = KhachHang.MatKhau AND KhachHang.Ban = 0)
	BEGIN
	SET @OK = 1
	END
	ELSE
	BEGIN
	SET @OK = 0
	END
COMMIT TRANSACTION


GO

CREATE OR ALTER PROCEDURE p_DangKyTKKH @MABN varchar(10), @HoTen NVARCHAR(255), @NgaySinh DATE, @DiaChi NVARCHAR(255),@SoDienThoai NVARCHAR(20), @MatKhau NVARCHAR(255)
AS
BEGIN TRANSACTION
	IF EXISTS (SELECT * FROM KhachHang WHERE KhachHang.MaBN = @MABN) OR EXISTS (SELECT * FROM KhachHang WHERE KhachHang.SoDienThoai = @SoDienThoai)
	BEGIN
		RAISERROR(N'Số tài khoản hoặc số điện thoại đã tồn tại',14,1)
		RETURN
	END
	ELSE
	BEGIN
		INSERT INTO KhachHang VALUES (@MABN,@HoTen,@NgaySinh,@DiaChi,@SoDienThoai,@MatKhau,0) 
	END
COMMIT TRANSACTION
GO
CREATE OR ALTER PROCEDURE p_DangKyLichHenKH @NGAYGIO DATETIME, @MABN VARCHAR(10), @MANHASI VARCHAR(10)

AS
BEGIN TRANSACTION
	DECLARE @THU VARCHAR(10)
	SET @THU = DATEPART(dw,@NGAYGIO)
	IF EXISTS (SELECT * FROM NhaSi WHERE NhaSi.MaNhaSi = @MANHASI AND NhaSi.lichlam LIKE '%' + @THU + '%')
	BEGIN
	RAISERROR(N'Lịch hẹn đặt không nằm trong thứ làm việc của bác sĩ',14,1)
	END
	IF EXISTS (SELECT * FROM LichHen WHERE LichHen.MaNhaSi = @MANHASI AND LichHen.NgayGio = @NGAYGIO)
	BEGIN
	RAISERROR(N'Lịch hẹn đặt đã bị trùng giờ với một lịch hẹn khác',14,1)
	END
	ELSE
	BEGIN
	INSERT INTO LichHen VALUES (@NGAYGIO,@MABN,@MANHASI,0)
	END
COMMIT TRANSACTION
GO
CREATE OR ALTER PROCEDURE p_XemInfoBn @MABN VARCHAR(10)
AS
BEGIN TRANSACTION
	IF NOT EXISTS (SELECT * FROM KhachHang WHERE KhachHang.MaBN = @MABN)
	BEGIN
		RAISERROR(N'Thông tin cá nhân không tồn tại',14,1)
	END
	ELSE
	BEGIN
		SELECT * FROM KhachHang WHERE KhachHang.MaBN = @MABN
	END

COMMIT TRANSACTION
GO
CREATE OR ALTER PROCEDURE p_XemHoSoBn @MABN VARCHAR(10)
AS
BEGIN TRANSACTION
	IF NOT EXISTS (SELECT * FROM HoSoBenhNhan WHERE HoSoBenhNhan.MaBN = @MABN)
	BEGIN
		RAISERROR(N'Hồ sơ không tồn tại',14,1)
	END
	ELSE
	BEGIN
		SELECT * FROM HoSoBenhNhan WHERE HoSoBenhNhan.MaBN = @MABN
	END

COMMIT TRANSACTION

GO
CREATE OR ALTER PROCEDURE p_KtraTKNS @MaNhaSi VARCHAR(10), @MATKHAU NVARCHAR(255),
@OK BIT OUT
AS
BEGIN TRANSACTION
	IF EXISTS(SELECT * FROM NhaSi WHERE @MaNhaSi = NhaSi.MaNhaSi AND @MATKHAU = NhaSi.MatKhau AND NhaSi.Ban = 0)
	BEGIN
	SET @OK = 1
	END
	ELSE
	BEGIN
	SET @OK = 0
	END
COMMIT TRANSACTION

select * from KhachHang