use QuanLyPhongKhamNhaKhoa_HQT
go

CREATE OR ALTER PROCEDURE p_KtraTKNV @MANV VARCHAR(20), @MATKHAU NVARCHAR(255),
@OK BIT OUT
AS
BEGIN TRANSACTION
	IF EXISTS(SELECT * FROM NhanVien WHERE @MANV = NhanVien.MaNV AND @MATKHAU = NhanVien.MatKhau)
	BEGIN
	SET @OK = 1
	END
	ELSE
	BEGIN
	SET @OK = 0
	END
COMMIT TRANSACTION



